# Generated by Django 3.2.19 on 2023-06-22 12:43

import CarCollectionApp.car_collection.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank='False', choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10, null='False')),
                ('model', models.CharField(blank='False', max_length=20, null='False', validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(blank='False', null='False', validators=[CarCollectionApp.car_collection.validators.validate_car_year])),
                ('image_url', models.URLField(blank='False', null='False')),
                ('price', models.FloatField(blank='False', null='False', validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
    ]
