# Generated by Django 3.2.19 on 2023-06-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank='True', max_length=30, null='True'),
            preserve_default='True',
        ),
    ]
